@startuml ユースケース図

    left to right direction

    actor ユーザー

    package サークル {
        usecase サークルを作成する 
        usecase サークルに参加する 
    }

    ユーザー -- サークルを作成する
    ユーザー -- サークルに参加する
    
@enduml