' 1. 名前は書こう
@startuml ユースケース図

    left to right direction

    actor ユーザー
    actor 管理ユーザー

    package 会員{
        usecase 会員登録をする
        usecase 会員情報を確認する
        usecase 会員情報を変更する
    }

    package 後で作る{
        usecase ログインする
        
        usecase パスワードを変更する
        
        

        usecase 現在のポイントを確認する
        usecase 失効予定のポイントを確認する
        usecase ポイントの履歴を確認する

        usecase 利用可能なクーポン一覧を確認する
        usecase クーポンの履歴を確認する

        usecase 商品を閲覧する
        usecase 商品を検索する
        usecase ポイント専用商品をカートに入れる

        usecase 商品をカートに入れる
        usecase 商品をカートから削除する
        usecase カート内商品の数量を変更する
        usecase プロモーションをカートに適用する

        usecase 注文手続きをする
        usecase 注文をする
        usecase 決済を行う
        usecase ポイントを消費する
        usecase クーポンを消費する
        usecase 注文履歴を確認する
        usecase 配送状況を確認する
    }

    ユーザー -- ログインする

    ' ' 9. メモ
    ' note bottom of 閲覧者 : 試合を予想したりする
    
@enduml