@startuml practice-ec-webapi

package User{
    package Domain{

        class User{
            ユーザーID
            ユーザー名
            ユーザー名フリガナ
            メールアドレス
            パスワード
            郵便番号
            住所
            電話番号
            生年月
            メールマガジン購読
        }

        note top of User : * ユーザー間でメールアドレスの\n   重複はできない
       
    }
    package Usecase{
        class UserGetAction{
            ユーザー情報を取得する()
        }
        class UserRegisterAction{
            ユーザーを新規登録する()
        }
        class UserUpdateAction{
            ユーザー情報を更新する()
        }
    }
    package Infrastructure{
    }

    Domain <.do. Usecase
    Domain <.do. Infrastructure
}
   

@enduml