@startuml practice-ec-webapi

package Catalog{
    package Domain{

        class ProductList{
            <List> 商品
            商品を追加する()
        }

        class Product{
            商品ID
            商品名
            カテゴリ
            税込価格
            消費税
            レビュー平均値
        }

         class ReserveProduct{
            商品ID
            商品名
            カテゴリ
            税込価格
            消費税
        }

        class PointProduct{
            商品ID
            商品名
            カテゴリ
            必要ポイント
            レビュー平均値
        }

        class Category{
            カテゴリID
            カテゴリ名
        }
       
    }
    package Usecase{
        class ProductListGetAction{
            商品情報一覧を取得する()
        }

        note top of ProductListGetAction : 取得の条件を細かく指定できる\n * カテゴリ指定\n * 好レビュー順指定\n * 件数指定\n * オフセット指定\n など

        class CategoryListGetAction{
            カテゴリ一覧を取得する()
        }
    }
    package Infrastructure{
    }

    Domain <.do. Usecase
    Domain <.do. Infrastructure
}
   

@enduml